owl:
  name: OWLTask
  dataloader:
    batch_size: 8
    num_workers: 8
  dataset:
    name: OWLDataset
    root: ./data/OwlEval
  gen_kwargs:
    max_new_tokens: 512
    top_k: 5
    num_beams: 1
    do_sample: False
    use_cache: True
